// DuckDB integration: load pipeline outputs into dana.duckdb
// Python scripts take barcode_dir as argv[1], chdir into it, open dana.duckdb.
// Uses val(barcode_dir) since scripts operate on the published output directory
// (host filesystem), not the Nextflow work directory.
// maxForks=1 to prevent concurrent DuckDB access

// Canonical 136 reverse-complement-collapsed tetranucleotide column names
// Generated by tetramer_freqs_esom.pl; fixed set used for tnfs.txt header
def TETRA_COLS = 'seqid\tAAAA\tAAAC\tAAAG\tAAAT\tAACA\tAACC\tAACG\tAACT\tAAGA\tAAGC\tAAGG\tAAGT\tAATA\tAATC\tAATG\tAATT\tACAA\tACAC\tACAG\tACAT\tACCA\tACCC\tACCG\tACCT\tACGA\tACGC\tACGG\tACGT\tACTA\tACTC\tACTG\tAGAA\tAGAC\tAGAG\tAGAT\tAGCA\tAGCC\tAGCG\tAGCT\tAGGA\tAGGC\tAGGG\tAGTA\tAGTC\tAGTG\tATAA\tATAC\tATAG\tATAT\tATCA\tATCC\tATCG\tATGA\tATGC\tATGG\tATTA\tATTC\tATTG\tCAAA\tCAAC\tCAAG\tCACA\tCACC\tCACG\tCAGA\tCAGC\tCAGG\tCATA\tCATC\tCATG\tCCAA\tCCAC\tCCAG\tCCCA\tCCCC\tCCCG\tCCGA\tCCGC\tCCGG\tCCTA\tCCTC\tCGAA\tCGAC\tCGAG\tCGCA\tCGCC\tCGCG\tCGGA\tCGGC\tCGTA\tCGTC\tCTAA\tCTAC\tCTAG\tCTCA\tCTCC\tCTGA\tCTGC\tCTTA\tCTTC\tGAAA\tGAAC\tGACA\tGACC\tGAGA\tGAGC\tGATA\tGATC\tGCAA\tGCAC\tGCCA\tGCCC\tGCGA\tGCGC\tGCTA\tGGAA\tGGAC\tGGCA\tGGCC\tGGGA\tGGTA\tGTAA\tGTAC\tGTCA\tGTGA\tGTTA\tTAAA\tTACA\tTAGA\tTATA\tTCAA\tTCCA\tTCGA\tTGAA\tTGCA\tTTAA'

process DB_INTEGRATION {
    tag "${barcode_dir}"
    label 'process_medium'
    conda "${projectDir}/conda-envs/dana-tools"
    maxForks 1
    executor 'local'

    input:
    val barcode_dir

    output:
    val barcode_dir

    script:
    """
    if [ -d "${barcode_dir}/kraken" ] && ls "${barcode_dir}"/kraken/*.tsv >/dev/null 2>&1; then
        python3 ${params.danadir}/kraken_db.py "${barcode_dir}" || true
        python3 ${params.danadir}/krakenreport_db.py "${barcode_dir}" || true
    fi

    if [ -d "${barcode_dir}/prokka" ] || [ -d "${barcode_dir}/bakta" ]; then
        python3 ${params.danadir}/annotation_db.py "${barcode_dir}" || true
    fi

    if [ -d "${barcode_dir}/sketch" ] && ls "${barcode_dir}"/sketch/*.txt >/dev/null 2>&1; then
        python3 ${params.danadir}/sketch_db.py "${barcode_dir}" || true
    fi

    if [ -d "${barcode_dir}/tetra" ] && ls "${barcode_dir}"/tetra/*.lrn >/dev/null 2>&1; then
        if [ ! -s "${barcode_dir}/tnfs.txt" ]; then
            printf '${TETRA_COLS}\\n' > "${barcode_dir}/tnfs.txt"
        fi
        python3 ${params.danadir}/tetra_db.py "${barcode_dir}" || true
    fi
    """
}

// Post-DB cleanup: compress or delete source files after DuckDB import confirms
// results are loaded.  Runs after DB_INTEGRATION in batch mode.
// Strategy: gzip fa/ in place, delete kraken/sketch/tetra (data in DuckDB),
// delete prokka TSVs, gzip prokka .gff/.faa/.ffn.  Per-file approach is safe
// for watch mode where new files arrive between cleanup cycles.
// maxForks=1 since cleanup is I/O-bound and sequential is fine.

process CLEANUP {
    tag "${barcode_dir}"
    label 'process_low'
    conda "${projectDir}/conda-envs/dana-tools"
    maxForks 1
    executor 'local'

    input:
    val barcode_dir

    script:
    """
    DB="${barcode_dir}/dana.duckdb"
    if [ ! -f "\$DB" ]; then
        echo "[WARNING] No DuckDB at \$DB, skipping cleanup"
        exit 0
    fi

    imported_count=\$(python3 -c "
        import duckdb
        con = duckdb.connect('\$DB', read_only=True)
        print(con.execute('SELECT count(*) FROM import_log').fetchone()[0])
        con.close()
    " 2>/dev/null || echo 0)

    if [ "\$imported_count" -eq 0 ] 2>/dev/null; then
        echo "[WARNING] import_log empty for ${barcode_dir}, skipping cleanup"
        exit 0
    fi

    echo "[INFO] CLEANUP: \$imported_count files in import_log for ${barcode_dir}"
    before=\$(du -sh "${barcode_dir}" | cut -f1)

    # fa/: leave alone — Nextflow publishDir re-copies .fa on -resume,
    # so gzipping here just creates .fa + .fa.gz duplicates.
    # fa/ is not loaded into DuckDB; disk reclamation happens via MAG assembly.

    # kraken/, sketch/, tetra/: delete files already loaded into DuckDB
    # Keep .lengths files in tetra/ — needed by viz (not in DuckDB)
    for subdir in kraken sketch tetra; do
        [ ! -d "${barcode_dir}/\$subdir" ] && continue
        find "${barcode_dir}/\$subdir" -type f ! -name '*.lengths' -delete 2>/dev/null || true
        echo "[INFO] Deleted files in \$subdir/"
    done

    # prokka/bakta: delete loaded TSVs only.
    # Leave .gff/.faa/.ffn uncompressed — Nextflow publishDir re-copies on -resume.
    find "${barcode_dir}/prokka" -name 'PROKKA_*.tsv' -delete 2>/dev/null || true
    find "${barcode_dir}/bakta" -name '*.tsv' -delete 2>/dev/null || true
    echo "[INFO] Deleted annotation TSVs (prokka/bakta)"

    after=\$(du -sh "${barcode_dir}" | cut -f1)
    echo "[INFO] Space: \$before -> \$after"
    """
}

// Periodic DB sync for watch mode.
// Runs as a long-lived process with an internal sleep loop — in watch mode the
// pipeline never completes (watchPath keeps the DAG alive), so this process
// runs indefinitely alongside it.  Scans the output directory for barcode
// subdirectories and loads results into DuckDB.  The R scripts are idempotent
// (they use import_log to track what's already been loaded).

process DB_SYNC {
    tag "db-sync"
    label 'process_medium'
    conda "${projectDir}/conda-envs/dana-tools"
    maxForks 1
    executor 'local'

    input:
    val outdir           // absolute path to output directory
    val danadir          // path to R scripts directory
    val sync_seconds     // sleep interval between sync cycles
    val cleanup_enabled  // "true" or "false"
    val metadata_file    // path to sample metadata TSV (or "none")

    script:
    """
    run_cleanup() {
        local bdir="\$1"
        local DB="\${bdir}/dana.duckdb"
        [ ! -f "\$DB" ] && return 0

        local imported_count
        imported_count=\$(python3 -c "
            import duckdb
            con = duckdb.connect('\$DB', read_only=True)
            print(con.execute('SELECT count(*) FROM import_log').fetchone()[0])
            con.close()
        " 2>/dev/null || echo 0)

        [ "\$imported_count" -eq 0 ] 2>/dev/null && return 0

        echo "[INFO] CLEANUP: \$imported_count files in import_log for \$bdir"
        local before=\$(du -sh "\$bdir" | cut -f1)

        # fa/: leave alone — Nextflow publishDir re-copies .fa on -resume,
        # so gzipping here just creates .fa + .fa.gz duplicates.

        # kraken/, sketch/, tetra/: delete files (data lives in DuckDB)
        # Keep .lengths files in tetra/ — needed by viz (not in DuckDB)
        for subdir in kraken sketch tetra; do
            [ ! -d "\${bdir}/\$subdir" ] && continue
            find "\${bdir}/\$subdir" -type f ! -name '*.lengths' -delete 2>/dev/null || true
        done

        # prokka/bakta: delete loaded TSVs only.
        # Leave .gff/.faa/.ffn uncompressed — Nextflow publishDir re-copies on -resume.
        find "\${bdir}/prokka" -name 'PROKKA_*.tsv' -delete 2>/dev/null || true
        find "\${bdir}/bakta" -name '*.tsv' -delete 2>/dev/null || true

        local after=\$(du -sh "\$bdir" | cut -f1)
        echo "[INFO] CLEANUP \$bdir: \$before -> \$after"
    }

    tick=0
    last_tsne_time=0
    last_tsne_rows=0
    last_sync_files=0
    tsne_interval=3600  # Run t-SNE at most once per hour
    while true; do
        echo "[INFO] DB_SYNC tick=\${tick}: scanning ${outdir} for barcode directories"

        # Count pending data files to detect new data
        cur_files=\$(find ${outdir} -mindepth 4 -maxdepth 4 \\( -path '*/kraken/*.tsv' -o -path '*/sketch/*.txt' -o -path '*/tetra/*.lrn' -o -path '*/prokka/*' -o -path '*/bakta/*' \\) 2>/dev/null | wc -l)
        has_new_data=false
        if [ \$cur_files -ne \$last_sync_files ]; then
            has_new_data=true
        fi

        if [ "\$has_new_data" = "true" ]; then
            # Find all barcode directories (outdir/flowcell/barcodeNN)
            for barcode_dir in \$(find ${outdir} -mindepth 2 -maxdepth 2 -type d -name 'barcode*' 2>/dev/null | sort); do
                echo "[INFO] DB_SYNC: processing \${barcode_dir}"

                if [ -d "\${barcode_dir}/kraken" ] && ls "\${barcode_dir}"/kraken/*.tsv >/dev/null 2>&1; then
                    python3 ${danadir}/kraken_db.py "\${barcode_dir}" || true
                    python3 ${danadir}/krakenreport_db.py "\${barcode_dir}" || true
                fi

                if [ -d "\${barcode_dir}/prokka" ] || [ -d "\${barcode_dir}/bakta" ]; then
                    python3 ${danadir}/annotation_db.py "\${barcode_dir}" || true
                fi

                if [ -d "\${barcode_dir}/sketch" ] && ls "\${barcode_dir}"/sketch/*.txt >/dev/null 2>&1; then
                    python3 ${danadir}/sketch_db.py "\${barcode_dir}" || true
                fi

                if [ -d "\${barcode_dir}/tetra" ] && ls "\${barcode_dir}"/tetra/*.lrn >/dev/null 2>&1; then
                    if [ ! -s "\${barcode_dir}/tnfs.txt" ]; then
                        printf '${TETRA_COLS}\\n' > "\${barcode_dir}/tnfs.txt"
                    fi
                    python3 ${danadir}/tetra_db.py "\${barcode_dir}" || true
                fi

                # Post-sync cleanup if enabled
                if [ "${cleanup_enabled}" = "true" ]; then
                    run_cleanup "\${barcode_dir}"
                fi
            done

            last_sync_files=\$cur_files

            # Compute sample sketch distances for sample t-SNE
            sketch_script="${projectDir}/viz/preprocess/compute_sketches.sh"
            viz_output="${outdir}/viz"
            sketch_tsv="\${viz_output}/sketch_distances.tsv"
            if [ -f "\${sketch_script}" ]; then
                echo "[INFO] DB_SYNC tick=\${tick}: computing sketch distances"
                mkdir -p "\${viz_output}"
                bash "\${sketch_script}" --input "${outdir}" --output "\${sketch_tsv}" \
                    --env "${projectDir}/conda-envs/dana-bbmap" 2>&1 | sed 's/^/  [VIZ] /' || true
            fi

            # Regenerate viz JSON when new data was imported
            viz_preprocess="${projectDir}/viz/preprocess/preprocess.py"
            preprocess_args="--input ${outdir} --output \${viz_output}"
            if [ -f "\${sketch_tsv}" ]; then
                preprocess_args="\${preprocess_args} --sketch-distances \${sketch_tsv}"
            fi
            if [ "${metadata_file}" != "none" ] && [ -f "${metadata_file}" ]; then
                preprocess_args="\${preprocess_args} --metadata ${metadata_file}"
            fi
            if [ -f "\${viz_preprocess}" ]; then
                echo "[INFO] DB_SYNC tick=\${tick}: running viz preprocess"
                mkdir -p "\${viz_output}"
                python3 "\${viz_preprocess}" \${preprocess_args} 2>&1 | sed 's/^/  [VIZ] /' || true
            fi
        else
            echo "[INFO] DB_SYNC tick=\${tick}: no new data files (count=\${cur_files})"
        fi

        # t-SNE: run at most once per hour, and only if new data arrived since last t-SNE
        read_tsne="${projectDir}/viz/preprocess/compute_read_tsne.py"
        viz_output="${outdir}/viz"
        if [ -f "\${read_tsne}" ]; then
            now=\$(date +%s)
            elapsed=\$((now - last_tsne_time))
            # Count total tetra_data rows across all samples
            cur_rows=0
            for barcode_dir in \$(find ${outdir} -mindepth 2 -maxdepth 2 -type d -name 'barcode*' 2>/dev/null); do
                db="\${barcode_dir}/dana.duckdb"
                [ -f "\$db" ] || continue
                nr=\$(python3 -c "import duckdb; c=duckdb.connect('\$db',read_only=True); print(c.execute('SELECT count(*) FROM tetra_data').fetchone()[0])" 2>/dev/null || echo 0)
                cur_rows=\$((cur_rows + nr))
            done
            if [ \$elapsed -ge \$tsne_interval ] && [ \$cur_rows -gt \$last_tsne_rows ]; then
                echo "[INFO] DB_SYNC tick=\${tick}: running read t-SNE (\${cur_rows} rows, \${last_tsne_rows} last time)"
                mkdir -p "\${viz_output}"
                python3 "\${read_tsne}" --input "${outdir}" --output "\${viz_output}" 2>&1 | sed 's/^/  [VIZ] /' || true
                last_tsne_time=\$(date +%s)
                last_tsne_rows=\$cur_rows
            else
                echo "[INFO] DB_SYNC tick=\${tick}: skipping t-SNE (elapsed=\${elapsed}s, rows=\${cur_rows}, last=\${last_tsne_rows})"
            fi
        fi

        echo "[INFO] DB_SYNC tick=\${tick}: complete, sleeping ${sync_seconds}s"
        tick=\$((tick + 1))
        sleep ${sync_seconds}
    done
    """
}
